--We can create a generic audit table to store statement-level triggers:

CREATE TABLE employees_audit (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type    VARCHAR2(50),
    action_date    DATE,
    affected_table VARCHAR2(50),
    total_rows     NUMBER,
    db_user        VARCHAR2(30),
    os_user        VARCHAR2(30),
    client_ip      VARCHAR2(50),
    session_id     VARCHAR2(50)
);