/* 
QUESTION:
-----------
Create a mechanism to log every user login into the database. 
For each login, store the following information in a table:

1. A unique log ID
2. Username of the logged-in user
3. The session ID
4. The timestamp of login

You should implement this using a **table** and a **database-level trigger** 
that fires **after any user logs on**. 

Also, demonstrate how to check that the trigger works by querying the log table.
*/

/* 
SOLUTION:
-----------
Step 1: Create the log table
*/
CREATE TABLE USER_LOG (
    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unique identifier for each log entry
    USERNAME VARCHAR2(50),                                     -- Stores the username of the logged-in user
    SESSION_ID NUMBER,                                         -- Tracks the session ID of the user
    LOGON_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP            -- Records the logon time (defaults to the current time)
);

/*
Step 2: Create a database-level trigger to log user logins
*/
CREATE OR REPLACE TRIGGER trg_logon_audit
AFTER LOGON ON DATABASE
BEGIN
    -- Insert a record into the USER_LOG table for every user logon
    INSERT INTO USER_LOG (USERNAME, SESSION_ID, LOGON_TIME)
    VALUES (
        USER,                                      -- Captures the username of the logged-in user
        SYS_CONTEXT('USERENV', 'SESSIONID'),       -- Retrieves the current session ID
        SYSTIMESTAMP                               -- Captures the current timestamp for the logon
    );
END trg_logon_audit;
/

-- Grant necessary privileges if needed (for testing with other users)
-- GRANT CREATE TRIGGER TO your_user;
-- GRANT INSERT ON USER_LOG TO other_users;

/*
TEST:
------
1. Log out and log back in as a user (or open a new session in SQL Developer/SQL*Plus).
2. Query the USER_LOG table to verify the log entry was recorded.

Example:

*/
SELECT * FROM USER_LOG
ORDER BY LOGON_TIME DESC;

/*
EXPECTED RESULT:
-----------------
You should see a row with:

- LOG_ID: auto-generated unique ID
- USERNAME: the user who just logged in
- SESSION_ID: session number assigned by Oracle
- LOGON_TIME: the exact timestamp of login
*/