/* ============================================================
   TITLE: Compound DML Audit Trigger for Tracking INSERT, UPDATE,
          DELETE Operations and Affected Rows on Employees Table
   ============================================================ */


/* ============================================================
   STEP 1: DROP AUDIT TABLE IF IT EXISTS
   ============================================================ */
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE employees_audit CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

/* ============================================================
   STEP 2: CREATE AUDIT TABLE
   ============================================================ */
CREATE TABLE employees_audit(
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(50),
    action_date DATE,
    affected_rows NUMBER,
    db_user VARCHAR2(52),
    session_id VARCHAR2(50)
);

/* ============================================================
   STEP 3: DROP TRIGGER IF IT EXISTS
   ============================================================ */
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER emp_audit_trg';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

/* ============================================================
   STEP 4: CREATE COMPOUND TRIGGER
   - Counts rows at row-level
   - Inserts audit once at statement-level
   ============================================================ */
CREATE OR REPLACE TRIGGER emp_audit_trg
FOR INSERT OR UPDATE OR DELETE ON employees
COMPOUND TRIGGER

    /* Shared variable across all timing points */
    v_total  NUMBER := 0;
    v_action VARCHAR2(50);

    /* ========================================================
       BEFORE STATEMENT
       - Identify operation type once per statement
       ======================================================== */
    BEFORE STATEMENT IS
    BEGIN
        IF INSERTING THEN 
            v_action := 'INSERT STATEMENT';
        ELSIF UPDATING THEN 
            v_action := 'UPDATE STATEMENT';
        ELSIF DELETING THEN 
            v_action := 'DELETE STATEMENT';
        END IF;
    END BEFORE STATEMENT;

    /* ========================================================
       AFTER EACH ROW
       - Increment counter for each affected row
       ======================================================== */
    AFTER EACH ROW IS
    BEGIN
        v_total := v_total + 1;
    END AFTER EACH ROW;

    /* ========================================================
       AFTER STATEMENT
       - Insert audit record once
       ======================================================== */
    AFTER STATEMENT IS
    BEGIN
        INSERT INTO employees_audit (
            action_type,
            action_date,
            affected_rows,
            db_user,
            session_id
        )
        VALUES (
            v_action,
            SYSDATE,
            v_total,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','SESSIONID')
        );
    END AFTER STATEMENT;

END;
/

/* ============================================================
   STEP 5: TEST THE TRIGGER
   ============================================================ */

/* Insert test */
INSERT INTO employees (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, 
    HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, 
    MANAGER_ID, DEPARTMENT_ID, BONUS
) 
VALUES (
    56, 'Eric', 'TEST', 'eric@example.com', '0780000000', 
    SYSDATE, 'IT_PROG', 6000, NULL, NULL, 20, 300
);

/* Update test */
UPDATE employees 
SET salary = salary + 1000 
WHERE department_id = 20;

/* Delete test */
DELETE FROM employees 
WHERE employee_id = 56;

/* ============================================================
   STEP 6: VERIFY AUDIT RESULTS
   ============================================================ */
SELECT * FROM employees_audit;