/* ============================================================
   STEP 1: DROP AUDIT TABLE IF IT EXISTS
   - This block attempts to drop the table.
   - If the table does not exist, it ignores the error.
   ============================================================ */
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE employees_audit CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- Ignore "table does not exist" error
            RAISE;
        END IF;
END;
/

/* ============================================================
   STEP 2: CREATE AUDIT TABLE
   - This table will store all audit logs for DML operations.
   ============================================================ */
CREATE TABLE employees_audit(
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(50),     -- Type of operation (INSERT, UPDATE, DELETE)
    action_date DATE,             -- Date when action occurred
    affected_rows NUMBER,         -- Number of rows affected
    db_user VARCHAR2(52),         -- Database user who performed the action
    session_id VARCHAR2(50)       -- Session ID of the user
);

/* ============================================================
   STEP 3: DROP TRIGGER IF IT EXISTS
   ============================================================ */
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER emp_audit_trg';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN -- Ignore "trigger does not exist"
            RAISE;
        END IF;
END;
/

/* ============================================================
   STEP 4: CREATE TRIGGER
   - This is a statement-level trigger.
   - It fires AFTER INSERT, UPDATE, or DELETE on EMPLOYEES table.
   ============================================================ */
CREATE OR REPLACE TRIGGER emp_audit_trg
AFTER INSERT OR UPDATE OR DELETE ON employees

DECLARE 
    v_total NUMBER;        -- Stores number of affected rows
    v_action VARCHAR2(50); -- Stores action type
BEGIN

    /* Determine the type of DML operation */
    IF INSERTING THEN 
        v_action := 'INSERT STATEMENT';
    ELSIF UPDATING THEN 
        v_action := 'UPDATE STATEMENT';
    ELSIF DELETING THEN 
        v_action := 'DELETE STATEMENT';
    END IF;

    /* Get number of rows affected by the DML statement */
    v_total := SQL%ROWCOUNT;

    /* Insert audit record */
    INSERT INTO employees_audit (
        action_type,
        action_date, 
        affected_rows,
        db_user,
        session_id
    ) 
    VALUES(
        v_action,
        SYSDATE,
        v_total, 
        SYS_CONTEXT('USERENV','SESSION_USER'),
        SYS_CONTEXT('USERENV','SESSIONID')
    );

END;
/

/* ============================================================
   STEP 5: TEST THE TRIGGER
   - Perform an INSERT operation
   ============================================================ */
INSERT INTO EMPLOYEES (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, 
    HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, 
    MANAGER_ID, DEPARTMENT_ID, BONUS
) 
VALUES (
    55, 'Alice', 'MUSAYIDIRE', 'aliceee@example.com', '0788746969', 
    SYSDATE, 'IT_PROG', 5000, NULL, NULL, 10, 500
);

/* ============================================================
   STEP 6: CHECK AUDIT RESULTS
   ============================================================ */
SELECT * FROM employees_audit;