-- ============================================================================================
-- 1. Drop Audit Table if exists
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employees_audit CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN  -- ignore table not exists
            RAISE;
        END IF;
END;
/
-- ============================================================================================

-- 2. Create function to get client IP
CREATE OR REPLACE FUNCTION get_client_info
RETURN VARCHAR2
IS
BEGIN
    RETURN SYS_CONTEXT('USERENV','IP_ADDRESS');
END;
/
-- Test the function
SELECT get_client_info() AS client_ip FROM dual;
-- ============================================================================================

-- 3. Create Audit Table
CREATE TABLE employees_audit (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type    VARCHAR2(20),
    action_date    DATE,
    affected_table VARCHAR2(50),
    total_rows     NUMBER,
    db_user        VARCHAR2(30),
    os_user        VARCHAR2(30),
    client_ip      VARCHAR2(50),
    session_id     VARCHAR2(50)
);
-- ============================================================================================

-- 4. Create a single trigger for all DML operations
CREATE OR REPLACE TRIGGER emp_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON employees
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO employees_audit (
            action_type,
            action_date,
            affected_table,
            total_rows,
            db_user,
            os_user,
            client_ip,
            session_id
        ) VALUES (
            'INSERT',
            SYSDATE,
            'EMPLOYEES',
            1,  -- one row affected
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );

    ELSIF UPDATING THEN
        INSERT INTO employees_audit (
            action_type,
            action_date,
            affected_table,
            total_rows,
            db_user,
            os_user,
            client_ip,
            session_id
        ) VALUES (
            'UPDATE',
            SYSDATE,
            'EMPLOYEES',
            1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );

    ELSIF DELETING THEN
        INSERT INTO employees_audit (
            action_type,
            action_date,
            affected_table,
            total_rows,
            db_user,
            os_user,
            client_ip,
            session_id
        ) VALUES (
            'DELETE',
            SYSDATE,
            'EMPLOYEES',
            1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );

    END IF;
END;
/
-- ============================================================================================

-- 5. TEST THE TRIGGER

-- Insert test
INSERT INTO employees (
    employee_id, first_name, last_name, email,
    phone_number, hire_date, job_id, salary,
    department_id
) VALUES (
    101, 'Alice', 'MUSAYIDIRE', 'alice@example.com',
    '0788746969', SYSDATE, 'IT_PROG', 5000,
    10
);

-- Update test
UPDATE employees
SET salary = salary + 500
WHERE department_id = 10;

-- Delete test
DELETE FROM employees
WHERE employee_id = 101;

-- Check audit log
SELECT * FROM employees_audit ORDER BY audit_id;