-- ============================================================================================
-- EMPLOYEE AUDIT & TAX APPLICATION
-- This script tracks all DML operations on EMPLOYEES
-- and automatically calculates RSSB tax (5% of salary).
-- All steps, functions, and triggers are in a single editor.
-- Questions are embedded for learning purposes.
-- ============================================================================================

-- 1. Drop audit table if exists
-- Q: Why drop the table first?
-- A: To avoid errors if the script is rerun.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employees_audit CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- Table does not exist
            RAISE;
        END IF;
END;
/

-- 2. Create function to get client IP
-- Q: Why use a function for client IP?
-- A: So triggers can easily capture which client/session performed the operation.
CREATE OR REPLACE FUNCTION get_client_info
RETURN VARCHAR2
IS
BEGIN
    RETURN SYS_CONTEXT('USERENV','IP_ADDRESS');
END;
/
-- Test function
SELECT get_client_info() AS client_ip FROM dual;

-- 3. Create function to calculate RSSB tax
-- Q: Why a separate function?
-- A: Makes tax calculation reusable in triggers, reports, or procedures.
CREATE OR REPLACE FUNCTION calc_rssb_tax(p_salary NUMBER)
RETURN NUMBER
IS
    v_tax NUMBER;
BEGIN
    v_tax := p_salary * 0.05; -- Example: RSSB = 5% of salary
    RETURN v_tax;
END;
/
-- Test function
SELECT calc_rssb_tax(5000) AS rssb_tax FROM dual;

-- 4. Create audit table
-- Q: What columns are required for auditing?
-- A: Operation type, timestamp, affected table, row info, user, OS, IP, session.
CREATE TABLE employees_audit (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type    VARCHAR2(20),
    action_date    DATE,
    affected_table VARCHAR2(50),
    total_rows     NUMBER,
    db_user        VARCHAR2(30),
    os_user        VARCHAR2(30),
    client_ip      VARCHAR2(50),
    session_id     VARCHAR2(50)
);

-- 5. Alter employees table to add RSSB tax column
-- Q: Why add rssb_tax column?
-- A: So we store calculated tax for each employee.
ALTER TABLE employees ADD (rssb_tax NUMBER);

-- 6. Create trigger for auditing + tax calculation
-- Q: Why combine audit + tax in one trigger?
-- A: Ensures every DML logs changes and automatically calculates RSSB tax.
CREATE OR REPLACE TRIGGER emp_audit_tax_trigger
BEFORE INSERT OR UPDATE OR DELETE ON employees
FOR EACH ROW
BEGIN
    -- ---------- RSSB TAX CALCULATION ----------
    IF INSERTING OR UPDATING THEN
        :NEW.rssb_tax := calc_rssb_tax(:NEW.salary);
        -- Q: Why BEFORE trigger for tax?
        -- A: So rssb_tax is updated in the row before it is saved.
    END IF;

    -- ---------- AUDIT LOG ----------
    IF INSERTING THEN
        INSERT INTO employees_audit (
            action_type, action_date, affected_table, total_rows,
            db_user, os_user, client_ip, session_id
        ) VALUES (
            'INSERT', SYSDATE, 'EMPLOYEES', 1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );

    ELSIF UPDATING THEN
        INSERT INTO employees_audit (
            action_type, action_date, affected_table, total_rows,
            db_user, os_user, client_ip, session_id
        ) VALUES (
            'UPDATE', SYSDATE, 'EMPLOYEES', 1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );

    ELSIF DELETING THEN
        INSERT INTO employees_audit (
            action_type, action_date, affected_table, total_rows,
            db_user, os_user, client_ip, session_id
        ) VALUES (
            'DELETE', SYSDATE, 'EMPLOYEES', 1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );
    END IF;
END;
/

-- 7. TEST THE APPLICATION
-- Insert employee (RSSB tax auto-calculated, audit recorded)
INSERT INTO employees (
    employee_id, first_name, last_name, email,
    phone_number, hire_date, job_id, salary, department_id
) VALUES (
    101, 'Alice', 'MUSAYIDIRE', 'alice@example.com',
    '0788746969', SYSDATE, 'IT_PROG', 5000, 10
);

-- Update salary (RSSB tax auto-updated, audit recorded)
UPDATE employees
SET salary = salary + 500
WHERE employee_id = 101;

-- Delete employee (audit recorded)
DELETE FROM employees
WHERE employee_id = 101;

-- Check audit log
SELECT * FROM employees_audit ORDER BY audit_id;

-- Check RSSB tax calculation
SELECT employee_id, first_name, salary, rssb_tax FROM employees;

-- Q: What happens after running the tests?
-- A: Each DML logs into audit table and RSSB tax is automatically calculated for inserted/updated rows.