-- ============================================================================================
-- EMPLOYEE AUDIT APPLICATION
-- This script sets up auditing for the EMPLOYEES table.
-- It tracks INSERT, UPDATE, DELETE operations including user info and client IP.
-- Questions are embedded to help understand each step.
-- ============================================================================================

-- ============================================================================================
-- 1. Drop the audit table if it already exists
-- Q: Why do we drop the table first?
-- A: To make sure we can rerun the script without errors.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employees_audit CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        -- Q: What does SQLCODE -942 mean?
        -- A: Table does not exist. We ignore this error.
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
-- ============================================================================================

-- ============================================================================================
-- 2. Create a function to get the client IP address
-- Q: Why do we need a function for client info?
-- A: So the trigger can record which computer or user session performed the operation.
CREATE OR REPLACE FUNCTION get_client_info
RETURN VARCHAR2
IS
BEGIN
    RETURN SYS_CONTEXT('USERENV','IP_ADDRESS');
END;
/
-- Q: How do we test the function?
SELECT get_client_info() AS client_ip FROM dual;
-- ============================================================================================

-- ============================================================================================
-- 3. Create the audit table
-- Q: What columns do we need for auditing?
-- A: We need operation type, timestamp, affected table, number of rows, DB user, OS user, client IP, session ID.
CREATE TABLE employees_audit (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Unique ID for each audit record
    action_type    VARCHAR2(20),  -- INSERT, UPDATE, DELETE
    action_date    DATE,           -- When the action occurred
    affected_table VARCHAR2(50),   -- Table affected (EMPLOYEES)
    total_rows     NUMBER,         -- How many rows affected (default 1 for row-level)
    db_user        VARCHAR2(30),   -- DB user performing the action
    os_user        VARCHAR2(30),   -- OS user
    client_ip      VARCHAR2(50),   -- Client IP
    session_id     VARCHAR2(50)    -- Session ID for traceability
);
-- ============================================================================================

-- ============================================================================================
-- 4. Create a trigger to audit all DML operations on EMPLOYEES
-- Q: Why do we use a single trigger for INSERT, UPDATE, DELETE?
-- A: It simplifies management and ensures all changes are logged consistently.
CREATE OR REPLACE TRIGGER emp_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON employees
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        -- Q: What info are we logging for an insert?
        -- A: Action type, timestamp, table, user, client IP, session.
        INSERT INTO employees_audit (
            action_type, action_date, affected_table, total_rows,
            db_user, os_user, client_ip, session_id
        ) VALUES (
            'INSERT', SYSDATE, 'EMPLOYEES', 1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );

    ELSIF UPDATING THEN
        -- Q: What info are we logging for an update?
        -- A: Same as insert but action_type = 'UPDATE'.
        INSERT INTO employees_audit (
            action_type, action_date, affected_table, total_rows,
            db_user, os_user, client_ip, session_id
        ) VALUES (
            'UPDATE', SYSDATE, 'EMPLOYEES', 1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );

    ELSIF DELETING THEN
        -- Q: What info are we logging for a delete?
        -- A: Same as above but action_type = 'DELETE'.
        INSERT INTO employees_audit (
            action_type, action_date, affected_table, total_rows,
            db_user, os_user, client_ip, session_id
        ) VALUES (
            'DELETE', SYSDATE, 'EMPLOYEES', 1,
            SYS_CONTEXT('USERENV','SESSION_USER'),
            SYS_CONTEXT('USERENV','OS_USER'),
            get_client_info(),
            SYS_CONTEXT('USERENV','SESSIONID')
        );
    END IF;
END;
/
-- ============================================================================================

-- ============================================================================================
-- 5. Test the audit trigger
-- Q: Why do we test all three operations?
-- A: To ensure the trigger correctly logs INSERT, UPDATE, and DELETE actions.

-- INSERT test
INSERT INTO employees (
    employee_id, first_name, last_name, email,
    phone_number, hire_date, job_id, salary, department_id
) VALUES (
    101, 'Alice', 'MUSAYIDIRE', 'alice@example.com',
    '0788746969', SYSDATE, 'IT_PROG', 5000, 10
);

-- UPDATE test
UPDATE employees
SET salary = salary + 500
WHERE department_id = 10;

-- DELETE test
DELETE FROM employees
WHERE employee_id = 101;

-- Check audit log
SELECT * FROM employees_audit ORDER BY audit_id;

-- Q: What should we see in the audit table?
-- A: Three rows corresponding to INSERT, UPDATE, DELETE with user, IP, session info.
-- ============================================================================================
